/*
 * Simple blogging APIs
 *
 * This is a simple blogging API
 *
 * API version: 1.0.0
 * Contact: gouthams.ku@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package restimpl

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/",
		Index,
	},

	{
		"AddBlogUsers",
		http.MethodPost,
		"/blogUsers",
		AddBlogUsers,
	},

	{
		"AddblogPosts",
		http.MethodPost,
		"/blogPosts",
		AddblogPosts,
	},

	{
		"DeleteBlogPosts",
		http.MethodDelete,
		"/blogPosts/:id",
		DeleteBlogPosts,
	},

	{
		"DeleteBlogUsers",
		http.MethodDelete,
		"/blogUsers/:id",
		DeleteBlogUsers,
	},

	{
		"GetblogPosts",
		http.MethodGet,
		"/blogPosts/:id",
		GetblogPosts,
	},

	{
		"GetblogUsers",
		http.MethodGet,
		"/blogUsers/:id",
		GetblogUsers,
	},

	{
		"SearchblogPosts",
		http.MethodGet,
		"/blogPosts",
		SearchblogPosts,
	},

	{
		"SearchblogUsers",
		http.MethodGet,
		"/blogUsers",
		SearchblogUsers,
	},

	{
		"UpdateBlogUsers",
		http.MethodPut,
		"/blogUsers/:id",
		UpdateBlogUsers,
	},

	{
		"UpdateblogPosts",
		http.MethodPut,
		"/blogPosts/:id",
		UpdateblogPosts,
	},
}
