/*
 * Simple blogging APIs
 *
 * This is a simple blogging API
 *
 * API version: 1.0.0
 * Contact: gouthams.ku@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package restimpl

type Error struct {
	Code string `json:"code"`

	Message string `json:"message"`
}
