/*
 * Simple blogging APIs
 *
 * This is a simple blogging API
 *
 * API version: 1.0.0
 * Contact: gouthams.ku@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package restimpl

import (
	"time"
)

type BlogUser struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name" binding:"required"`

	Email string `json:"email" binding:"required"`

	LastModifiedDate time.Time `json:"lastModifiedDate,omitempty"`
}
